# Generated by Django 3.2.6 on 2022-03-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biscuit',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cake',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
